### ISSUE TITLE
Amazing plugin

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [yduke/corona-virus-data#1]
I would like to own some plugin like this ;)

I recently created [COVID 19 global data web page](https://goonlinetools.com/covid19/global/) where everything is showing in full details.

If possible then link out to the webpage from the plugin for more detailed data.

Is there any way to take plugin complete source code right?  I would like to create COVID data plugin for other country

**Comment by yduke** [comment]
1 Sorry there is no plan to make external link in this plugin;
2 You can always download source code in the "code" section of this Github repo :)
